# Generated by Django 5.2.8 on 2025-12-01 04:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorturl', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='original_url',
            field=models.URLField(),
        ),
        migrations.AlterUniqueTogether(
            name='shorturl',
            unique_together={('user', 'original_url')},
        ),
    ]
